### ISSUE TITLE
与训练阶段loss的最终值

### ISSUE THREAD

**Issue by TXY123lalala** [Haochen-Wang409/DropPos#1]
您好，请问这个模型在预训练阶段结束后的loss大概在多少为佳呢？我不知道当前训练出的loss是否太大了

**Comment by Haochen-Wang409** [comment]
最终 loss 确实不小，我们会汇报位置预测的 Top-1 准确率，如果训练 200 epoch，大约在 65% 左右是比较正常的

**Comment by TXY123lalala** [comment]
好的谢谢您~
