### ISSUE TITLE
pretrain model

### ISSUE THREAD

**Issue by kendy201124** [Haochen-Wang409/DropPos#3]
大佬，请问方便释放预训练权重吗？

**Comment by Haochen-Wang409** [comment]
目前我们正在准备，准备完成后计划公开预训练后的权重

**Comment by Haochen-Wang409** [comment]
预训练与微调后的模型权重: https://pan.baidu.com/s/1xj9XiHgagKGJrJt88IfhLw?pwd=4gik
提取码4gik.
